/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "evchhgqmbiftvhokhkmb"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2Y2hoZ3FtYmlmdHZob2toa21iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU3NjQxMTEsImV4cCI6MjA5MTM0MDExMX0.D-cVZB3yCzWTwR2SQjMpXmRUkop-qSA4Y6tlveBFK14"